### ISSUE TITLE
collaborator依頼

### ISSUE THREAD

**Issue by tkitamoto** [tkcmada/stdenv_docker#1]
@tkcmada 
北本です。collaboratorの設定をお願いします。

**Comment by tkcmada** [comment]
added!

**Comment by tkcmada** [comment]
あーそうそう、プルリク不要でmasterに直接コミットしてもらってよいですから。

**Comment by tkitamoto** [comment]
>プルリク不要でmasterに直接コミットしてもらってよいですから。

了解です。
